import { Injectable, Logger } from '@nestjs/common';
import { promises as fs } from 'fs';
import * as path from 'path';
import { KanbanTaskSummary } from '../../jira/types/kanban-column.interface';
import { JiraTask } from '../../jira/types/jira-task.interface';
import { TaskExecutionResult } from '../task-executor.service';

@Injectable()
export class SimpleCodeExecutorService {
  private readonly logger = new Logger(SimpleCodeExecutorService.name);
  private readonly workspaceRoot = process.cwd();

  /**
   * Выполнить задачу создания кода
   */
  async executeCodeTask(
    task: KanbanTaskSummary | JiraTask,
  ): Promise<TaskExecutionResult> {
    const startTime = Date.now();
    this.logger.log(`Executing code task: ${task.key}`);

    try {
      const summary = 'summary' in task ? task.summary : task.fields.summary;
      const result = await this.handleCodeCreation(task.key, summary);

      const timeSpent = Math.round((Date.now() - startTime) / 1000 / 60); // в минутах

      return {
        taskKey: task.key,
        success: result.success,
        completedSteps: result.success ? 3 : 1,
        totalSteps: 3,
        timeSpent: Math.max(timeSpent, 1),
        errors: result.success ? [] : [result.error || 'Unknown error'],
        results: result.success ? [result.message || 'Task completed'] : [],
        finalStatus: result.success ? 'completed' : 'failed',
      };
    } catch (error) {
      const timeSpent = Math.round((Date.now() - startTime) / 1000 / 60);

      return {
        taskKey: task.key,
        success: false,
        completedSteps: 0,
        totalSteps: 3,
        timeSpent: Math.max(timeSpent, 1),
        errors: [`Execution failed: ${error.message}`],
        results: [],
        finalStatus: 'failed',
      };
    }
  }

  /**
   * Обработать создание кода
   */
  private async handleCodeCreation(
    taskKey: string,
    summary: string,
  ): Promise<{ success: boolean; message?: string; error?: string }> {
    try {
      // Определить тип задачи
      if (
        summary.toLowerCase().includes('создать сущность') ||
        summary.toLowerCase().includes('create entity')
      ) {
        return await this.createEntity(taskKey, summary);
      }

      if (
        summary.toLowerCase().includes('создай файл') ||
        summary.toLowerCase().includes('create file')
      ) {
        return await this.createFile(taskKey, summary);
      }

      // По умолчанию создаём простой файл
      return await this.createFile(taskKey, summary);
    } catch (error) {
      return {
        success: false,
        error: error.message,
      };
    }
  }

  /**
   * Создать сущность
   */
  private async createEntity(taskKey: string, summary: string) {
    const entityName =
      this.extractEntityName(summary) || `Task${taskKey.replace('-', '')}`;
    const fileName = `${entityName.toLowerCase()}.entity.ts`;
    const filePath = path.join(
      this.workspaceRoot,
      'src',
      'generated',
      'entities',
      fileName,
    );

    const content = `import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity('${entityName.toLowerCase()}s')
export class ${entityName} {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @Column({ nullable: true })
  description?: string;
}

// Generated by AI Agent for task ${taskKey}
// Created: ${new Date().toISOString()}
`;

    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, content, 'utf8');

    this.logger.log(`Entity created: ${filePath}`);

    return {
      success: true,
      message: `Entity "${entityName}" created at ${filePath}`,
    };
  }

  /**
   * Создать файл
   */
  private async createFile(taskKey: string, summary: string) {
    const fileName =
      this.extractFileName(summary) || `task-${taskKey.toLowerCase()}-file.ts`;
    const filePath = path.join(
      this.workspaceRoot,
      'src',
      'generated',
      fileName,
    );

    const content = `/**
 * Generated file for task ${taskKey}
 * Summary: ${summary}
 * Created: ${new Date().toISOString()}
 */

export class GeneratedTask${taskKey.replace('-', '')} {
  constructor() {
    console.log('Task ${taskKey} file created by AI Agent');
  }

  execute() {
    // TODO: Implement task logic
    console.log('Executing task ${taskKey}');
    return true;
  }
}

export default GeneratedTask${taskKey.replace('-', '')};
`;

    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, content, 'utf8');

    this.logger.log(`File created: ${filePath}`);

    return {
      success: true,
      message: `File "${fileName}" created at ${filePath}`,
    };
  }

  /**
   * Извлечь имя сущности
   */
  private extractEntityName(summary: string): string | null {
    const match = summary.match(
      /(?:создать сущность|create entity)\s*([a-zA-Zа-яА-Я]+)/i,
    );
    return match ? this.toPascalCase(match[1]) : null;
  }

  /**
   * Извлечь имя файла
   */
  private extractFileName(summary: string): string | null {
    const match = summary.match(
      /(?:создай файл|create file)\s*([a-zA-Z0-9\-_.]+)/i,
    );
    return match ? match[1] : null;
  }

  /**
   * Конвертировать в PascalCase
   */
  private toPascalCase(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
  }
}
